print("Lista de Compras - Supermercado")
print()
print("Producto \tCantidad")
print("Gaseosas \t2")
print("Serenitos \t6")
print("Leche \t\t6")
print("Jugo \t\t4")
print("Puré tomate \t2")
print("Galletitas \t4")