print("Lista de Compras")
print()
print("Almacén \t\tVerdulería \tGranja")
print("Gaseosa \t\tTomate \t\tMilanesa")
print("Mayonesa \t\tLechuga \tCaritas")
print("Papitas \t\tPapa \t\tPatitas")
print("\t \t\tHuevos")